name: TICS

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 3 * * 0" # Runs every Sunday at 03:00 UTC

jobs:
  build:
    runs-on: [self-hosted, linux, amd64, tiobe, jammy]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Run TICS analysis with github-action
        uses: tiobe/tics-github-action@88cb795a736d2ca885753bec6ed2c8b03e3f892f # v3
        with:
          mode: qserver
          project: vault-operator
          branchdir: ${{ GITHUB_WORKSPACE }}
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
