name: Build

on:
  workflow_call:

jobs:
  build-vault:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
    
      - name: Install LXD
        run: |
          sudo snap install lxd --channel=latest/stable
          sudo lxd waitready
          sudo lxd init --auto
          sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket
          lxc network set lxdbr0 ipv6.address none
          sudo usermod -a -G lxd $USER

      - name: Build Vault charm
        run: charmcraft pack --verbose

      - name: Archive Vault Charm
        uses: actions/upload-artifact@v4
        with:
          name: vault-charm
          path: vault_ubuntu-22.04-amd64.charm
          retention-days: 5

  build-kv-requirer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      
      - name: Install LXD
        run: |
          sudo snap install lxd --channel=latest/stable
          sudo lxd waitready
          sudo lxd init --auto
          sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket
          lxc network set lxdbr0 ipv6.address none
          sudo usermod -a -G lxd $USER

      - name: Build KV Requirer charm
        run: |
          cp lib/charms/vault_k8s/v0/vault_kv.py tests/integration/vault_kv_requirer_operator/lib/charms/vault_k8s/v0/vault_kv.py
          cd tests/integration/vault_kv_requirer_operator
          charmcraft pack --verbose

      - name: Archive KV Requirer Charm
        uses: actions/upload-artifact@v4
        with:
          name: kv-requirer-charm
          path: tests/integration/vault_kv_requirer_operator/vault-kv-requirer_ubuntu-22.04-amd64.charm
          retention-days: 5
