name: Integration Tests

on:
  workflow_call:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Vault Charm
        uses: actions/download-artifact@v4
        with:
          name: vault-charm
      
      - name: Fetch KV Requirer Charm
        uses: actions/download-artifact@v4
        with:
          name: kv-requirer-charm
    
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: 3.4/stable
          provider: lxd

      - name: Install tox
        run: pip install tox

      - name: Run integration tests
        run: tox -e integration
