name: Integration Tests

on:
  workflow_call:

jobs:
  integration-tests:
    runs-on: [self-hosted, linux, X64, jammy, xlarge]
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Charm Under Test
        uses: actions/download-artifact@v4
        with:
          name: built-charm
          path: built/
      
      - name: Get Charm Under Test Path
        id: charm-path
        run: echo "charm_path=$(find built/ -name '*.charm' -type f -print)" >> $GITHUB_OUTPUT
      
      - name: Fetch KV Requirer Charm
        uses: actions/download-artifact@v4
        with:
          name: kv-requirer-charm
          path: kv-requirer/
      
      - name: Get KV Requirer Charm Path
        id: kv-requirer-charm-path
        run: echo "charm_path=$(find kv-requirer/ -name '*.charm' -type f -print)" >> $GITHUB_OUTPUT
    
      - name: Setup operator environment
        run: |
          sudo snap install concierge --classic
          sudo concierge prepare -p machine --juju-channel "3.5/stable" --lxd-channel "5.21/stable" --extra-snaps astral-uv/latest/stable
          uv tool install tox --with tox-uv

      - name: Install uv
        run: sudo snap install --classic astral-uv

      - name: Install tox
        run: uv tool install tox --with tox-uv

      - name: Run integration tests
        run: |
          tox -e integration -- \
            --charm_path="${{ steps.charm-path.outputs.charm_path }}" \
            --kv_requirer_charm_path="${{ steps.kv-requirer-charm-path.outputs.charm_path }}"
