name: Integration Tests

on:
  workflow_call:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Charm Under Test
        uses: actions/download-artifact@v4
        with:
          name: built-charm
          path: built/
      
      - name: Get Charm Under Test Path
        id: charm-path
        run: echo "::set-output name=charm_path::$(find built -name '*.charm' -type f -print)"
      
      - name: Fetch KV Requirer Charm
        uses: actions/download-artifact@v4
        with:
          name: kv-requirer-charm
          path: kv-requirer/
      
      - name: Get KV Requirer Charm Path
        id: kv-requirer-charm-path
        run: echo "::set-output name=kv_requirer_charm_path::$(find kv-requirer -name '*.charm' -type f -print)"
    
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: 3.4/stable
          provider: lxd

      - name: Install tox
        run: pip install tox

      - name: Run integration tests
        run: tox -e integration -- --vault_charm_path="./vault_ubuntu-22.04-amd64.charm" --kv_requirer_charm_path="./vault-kv-requirer_ubuntu-22.04-amd64.charm"
