name: TICS Static Analysis

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 3 * * 0" # Runs every Sunday at 03:00 UTC

jobs:
  analyze:
    uses: canonical/identity-credentials-workflows/.github/workflows/tics-tox.yaml@tics-workflow
    with:
      project: vault-operator
    secrets:
      TICSAUTHTOKEN: ${{ secrets.TICSAUTHTOKEN }}

